// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9HiuiUTT1-nNF8xJOTeMLCiGy7tfRwsQ',
    appId: '1:399242916006:web:c4e39c656426fd970c8467',
    messagingSenderId: '399242916006',
    projectId: 'homemates-app',
    authDomain: 'homemates-app.firebaseapp.com',
    storageBucket: 'homemates-app.firebasestorage.app',
    measurementId: 'G-B9091B95VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv6k-wIk-saHCyNplqEArHeMqpQnj53c8',
    appId: '1:399242916006:android:dc78943848aaf3140c8467',
    messagingSenderId: '399242916006',
    projectId: 'homemates-app',
    storageBucket: 'homemates-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMThra9iaE5d9dNqtutfNkYNilCDw7Wg',
    appId: '1:399242916006:ios:c8bd8ac1f73014e40c8467',
    messagingSenderId: '399242916006',
    projectId: 'homemates-app',
    storageBucket: 'homemates-app.firebasestorage.app',
    iosBundleId: 'com.example.flatematesUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPMThra9iaE5d9dNqtutfNkYNilCDw7Wg',
    appId: '1:399242916006:ios:c8bd8ac1f73014e40c8467',
    messagingSenderId: '399242916006',
    projectId: 'homemates-app',
    storageBucket: 'homemates-app.firebasestorage.app',
    iosBundleId: 'com.example.flatematesUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9HiuiUTT1-nNF8xJOTeMLCiGy7tfRwsQ',
    appId: '1:399242916006:web:aed9fc1705f333000c8467',
    messagingSenderId: '399242916006',
    projectId: 'homemates-app',
    authDomain: 'homemates-app.firebaseapp.com',
    storageBucket: 'homemates-app.firebasestorage.app',
    measurementId: 'G-2DCLBREME4',
  );
}
